spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-service
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
